### PR TITLE
Bump to 2.0.1, fix recipe and add myself as maintainer

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
This PR is necessary for conda-forge/python-openstackclient-feedstock#6

**Comment by tschoonj** [comment]
@isuruf @beckermr @xhochy @marcelotrevisani 

This repo appears to have been abandoned and I would like to become a maintainer. I would be grateful if any of you could merge this PR in.

**Comment by xhochy** [comment]
Thanks @tschoonj , next time feel free to ping the more general `@conda-forge/core`

**Comment by tschoonj** [comment]
Thanks!

**Pull request merged**
